/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ContactForm from "./ContactForm";

const ContactSection: React.FC = () => {
  return (
    <div className="flex flex-col px-3 pb-16 mt-9 max-w-full font-bold text-center w-[1320px]">
      <div className="self-center px-5 py-2 text-sm tracking-wider leading-tight uppercase whitespace-nowrap bg-blue-600 bg-opacity-10 rounded-[50px] text-zinc-500">
        Contact
      </div>
      <h2 className="px-96 mt-2.5 w-full text-3xl leading-10 text-neutral-800 max-md:px-5 max-md:max-w-full">
        Need Help? <span className="text-zinc-500">Contact Us</span>
      </h2>
      <div className="flex flex-col mt-9 max-w-[1320px] w-[1319px] max-md:max-w-full">
        <div className="flex flex-wrap justify-center items-start w-full max-md:max-w-full">
          <div className="flex flex-col justify-center pt-6 max-w-[1320px] min-h-[561px] min-w-[240px] w-[509px] max-md:max-w-full">
            <div className="flex flex-col px-3 w-full min-h-[494px] max-md:max-w-full">
              <div className="flex flex-col px-8 pt-8 pb-24 w-full bg-white min-h-[494px] shadow-[0px_0px_20px_rgba(0,0,0,0.1)] max-md:px-5 max-md:max-w-full">
                <div className="flex w-full max-md:max-w-full">
                  <div className="flex flex-col items-start self-start pr-4 min-h-[44px] w-[59px]">
                    <div className="flex justify-center items-center px-3 w-11 h-11 bg-blue-600 bg-opacity-10 min-h-[44px] rounded-[50px]">
                      <div className="flex flex-col self-stretch my-auto w-5">
                        <img
                          loading="lazy"
                          src="https://cdn.builder.io/api/v1/image/assets/TEMP/ada8c7460c666258359d88ca2d8f0400b57d50f516b2971064b19f3f8a9f18b8?placeholderIfAbsent=true&apiKey=bc78d96b1bfe4229ab8bdab79a935f37"
                          alt=""
                          className="object-contain w-full aspect-square"
                        />
                      </div>
                    </div>
                  </div>
                  <div className="flex flex-col min-w-[240px] w-[255px]">
                    <h3 className="w-full text-lg font-bold leading-tight whitespace-nowrap text-neutral-800">
                      Address
                    </h3>
                    <p className="mt-1.5 w-full text-sm text-neutral-700">
                      A108 Adam Street, New York, NY 535022
                    </p>
                  </div>
                </div>
                <div className="flex mt-10 w-full max-md:max-w-full">
                  <div className="flex flex-col items-start self-start pr-4 min-h-[44px] w-[59px]">
                    <div className="flex justify-center items-center px-3 w-11 h-11 bg-blue-600 bg-opacity-10 min-h-[44px] rounded-[50px]">
                      <div className="flex flex-col self-stretch my-auto w-5">
                        <img
                          loading="lazy"
                          src="https://cdn.builder.io/api/v1/image/assets/TEMP/324d25fe9ce5a7b14fe10935406376276a2c4867a1492e4003569cfa3d156f7e?placeholderIfAbsent=true&apiKey=bc78d96b1bfe4229ab8bdab79a935f37"
                          alt=""
                          className="object-contain w-full aspect-square"
                        />
                      </div>
                    </div>
                  </div>
                  <div className="flex flex-col w-[113px]">
                    <h3 className="w-full text-lg font-bold leading-tight text-neutral-800">
                      Call Us
                    </h3>
                    <p className="mt-1.5 w-full text-sm text-neutral-700">
                      +1 5589 55488 55
                    </p>
                  </div>
                </div>
                <div className="flex mt-10 w-full max-md:max-w-full">
                  <div className="flex flex-col items-start self-start pr-4 min-h-[44px] w-[59px]">
                    <div className="flex justify-center items-center px-3 w-11 h-11 bg-blue-600 bg-opacity-10 min-h-[44px] rounded-[50px]">
                      <div className="flex flex-col self-stretch my-auto w-5">
                        <img
                          loading="lazy"
                          src="https://cdn.builder.io/api/v1/image/assets/TEMP/ff75e0b8837a2bbdf11c3c74157f3da17c5a8f86c4071149871051ed47557463?placeholderIfAbsent=true&apiKey=bc78d96b1bfe4229ab8bdab79a935f37"
                          alt=""
                          className="object-contain w-full aspect-square"
                        />
                      </div>
                    </div>
                  </div>
                  <div className="flex flex-col w-[121px]">
                    <h3 className="w-full text-lg font-bold leading-tight text-neutral-800">
                      Email Us
                    </h3>
                    <p className="mt-1.5 w-full text-sm whitespace-nowrap text-neutral-700">
                      info@example.com
                    </p>
                  </div>
                </div>
                <p className="mt-10 text-xl font-bold leading-6 text-black">
                  map <br />
                </p>
              </div>
            </div>
          </div>
          <ContactForm />
        </div>
      </div>
    </div>
  );
};

export default ContactSection;
