/**
 * This code was generated by Builder.io.
 */
import React from "react";

const ContactForm: React.FC = () => {
  return (
    <div className="flex flex-col justify-center px-3 pt-6 text-base max-w-[1320px] min-h-[623px] min-w-[240px] text-neutral-700 w-[770px] max-md:max-w-full">
      <form className="flex flex-col px-5 pt-1.5 pb-10 w-full bg-white min-h-[599px] shadow-[0px_0px_20px_rgba(0,0,0,0.1)] max-md:max-w-full">
        <div className="flex flex-col w-full max-md:max-w-full">
          <div className="flex flex-wrap">
            <div className="flex flex-col flex-1 grow shrink-0 justify-center pt-6 basis-0 min-h-[99px] w-fit">
              <div className="flex flex-col px-3 py-1 w-full max-w-[710px]">
                <label htmlFor="name" className="self-start">
                  Your Name
                </label>
                <input
                  id="name"
                  type="text"
                  className="flex shrink-0 mt-4 bg-white border border-solid border-neutral-700 border-opacity-20 h-[42px]"
                  aria-label="Your Name"
                />
              </div>
            </div>
            <div className="flex flex-col flex-1 grow shrink-0 justify-center pt-6 basis-0 min-h-[99px] w-fit">
              <div className="flex flex-col px-3 py-1 w-full max-w-[710px]">
                <label htmlFor="email" className="self-start">
                  Your Email
                </label>
                <input
                  id="email"
                  type="email"
                  className="flex shrink-0 mt-4 bg-white border border-solid border-neutral-700 border-opacity-20 h-[42px]"
                  aria-label="Your Email"
                />
              </div>
            </div>
          </div>
          <div className="flex flex-col justify-center pt-6 whitespace-nowrap min-h-[99px] max-md:max-w-full">
            <div className="flex flex-col px-3 py-1 w-full max-w-[710px] max-md:max-w-full">
              <label htmlFor="subject" className="self-start">
                Subject
              </label>
              <input
                id="subject"
                type="text"
                className="flex shrink-0 mt-3 bg-white border border-solid border-neutral-700 border-opacity-20 h-[43px] max-md:max-w-full"
                aria-label="Subject"
              />
            </div>
          </div>
          <div className="flex flex-col justify-center pt-6 whitespace-nowrap min-h-[288px] max-md:max-w-full">
            <div className="flex flex-col px-3 pt-1.5 w-full max-w-[710px] max-md:max-w-full">
              <label htmlFor="message" className="self-start">
                Message
              </label>
              <textarea
                id="message"
                className="flex shrink-0 mt-3 bg-white border border-solid border-neutral-700 border-opacity-20 h-[232px] max-md:max-w-full"
                aria-label="Message"
              ></textarea>
            </div>
          </div>
        </div>
        <button
          type="submit"
          className="flex flex-col justify-center pt-6 text-center text-white min-h-[68px] max-md:max-w-full"
        >
          <div className="px-8 py-2.5 bg-zinc-500 rounded-[50px] max-md:px-5">
            Send Message
          </div>
        </button>
      </form>
    </div>
  );
};

export default ContactForm;
